name: app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get:  
  http:
  get_storage:   
  splashscreen: ^1.3.5
  shared_preferences: ^2.0.5
  crypto: ^2.0.6
  #google_fonts: ^2.10.0
  flutter_svg: ^0.22.0
  fl_chart: ^0.36.2
  provider: ^5.0.0
  data_table_2: ^2.0.3
  cupertino_icons: ^1.0.2
  web_socket_channel: ^1.2.0
  curved_navigation_bar: ^1.0.3
  
dev_dependencies:
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/icons/
